### ISSUE TITLE
音頻轉碼前先更新下緩存

### ISSUE THREAD

**Issue by 599316527** [599316527/apple-tv-phoenixtv-proxy#10]
音頻的更新依賴於視頻列表的緩存，而音頻一天一次固定時間更新轉碼可能會錯視頻緩存的更新

**Comment by veetodo** [comment]
想请教下，如果我只更新音频，该如何安装。
实在不太会，谢谢！

**Comment by 599316527** [comment]
看另个单独的音频的项目吧 https://github.com/599316527/fetch-phoenixfm-qqsrx
